amcl:
  ros__parameters:
    use_sim_time: false

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

    robot_model_type: "differential"

    min_particles: 500
    max_particles: 2000

    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.2
    alpha4: 0.1
    alpha5: 0.2

    laser_model_type: "likelihood_field"
    max_beams: 90
    laser_min_range: 0.1
    laser_max_range: 12.0
    laser_likelihood_max_dist: 2.0

    update_min_d: 0.15
    update_min_a: 0.15

    pf_err: 0.05
    pf_z: 0.99

    resample_interval: 1
    transform_tolerance: 1.0
    tf_broadcast: true

    z_hit: 0.5
    z_rand: 0.5
    z_short: 0.05
    z_max: 0.05
    sigma_hit: 0.2
    lambda_short: 0.1

    scan_topic: scan


bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom

    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

    enable_groot_monitoring: false


controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 15.0

    min_x_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01

    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.15
      movement_time_allowance: 20.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.30
      stateful: true

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      debug_trajectory_details: false

      min_vel_x: 0.0
      max_vel_x: 0.4
      min_speed_xy: 0.05
      max_speed_xy: 0.4

      min_vel_theta: 0.0
      max_vel_theta: 0.6
      min_speed_theta: 0.05

      acc_lim_x: 1.0
      decel_lim_x: -1.0
      acc_lim_theta: 1.0
      decel_lim_theta: -1.0

      vx_samples: 15
      vtheta_samples: 20
      sim_time: 2.5

      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.05

      critics:
        - BaseObstacle
        - PathAlign
        - PathDist
        - GoalAlign
        - GoalDist
        - RotateToGoal
        - Oscillation

      BaseObstacle.scale: 0.02
      PathAlign.scale: 16.0
      PathAlign.forward_point_distance: 0.2
      PathDist.scale: 16.0
      GoalAlign.scale: 12.0
      GoalDist.scale: 12.0
      RotateToGoal.scale: 8.0


local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 10.0
      publish_frequency: 5.0

      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true

      width: 5
      height: 5
      resolution: 0.05

      footprint: "[[0.18,0.14],[0.18,-0.14],[-0.18,-0.14],[-0.18,0.14]]"

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          clearing: true
          marking: true
          obstacle_max_range: 2.5
          raytrace_max_range: 3.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.30
        cost_scaling_factor: 3.0

      always_send_full_costmap: true


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 1.0
      publish_frequency: 1.0

      global_frame: map
      robot_base_frame: base_link

      resolution: 0.05
      track_unknown_space: true

      footprint: "[[0.18,0.14],[0.18,-0.14],[-0.18,-0.14],[-0.18,0.14]]"

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          clearing: true
          marking: true
          obstacle_max_range: 2.5
          raytrace_max_range: 3.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.30
        cost_scaling_factor: 3.0

      always_send_full_costmap: true


planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0

    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: true
      allow_unknown: true
      tolerance: 0.5


recoveries_server:
  ros__parameters:
    use_sim_time: false
    cycle_frequency: 5.0

    recovery_plugins: ["spin", "back_up", "wait"]

    spin:
      plugin: "nav2_recoveries/Spin"
    back_up:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

    global_frame: odom
    robot_base_frame: base_link


map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "my_map.yaml"


robot_state_publisher:
  ros__parameters:
    use_sim_time: false

