<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.323" />
    <xacro:property name="base_width" value="0.137" />
    <xacro:property name="base_height" value="0.078" />

    <xacro:property name="wheel_radius" value="0.0435" />
    <xacro:property name="wheel_length" value="0.045" />

    <xacro:property name="wheel_effort_limit" value="10.0" />
    <xacro:property name="wheel_velocity_limit" value="10.0" />

    <!-- Sensor mounting height: 19 cm from base frame -->
    <xacro:property name="sensor_height" value="${base_height + 0.04}" />

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="yellow"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>

        <inertial>
            <mass value="5.0"/>
            <inertia ixx="0.1" ixy="0" ixz="0"
                     iyy="0.1" iyz="0"
                     izz="0.1"/>
        </inertial>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="grey"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>

            <inertial>
                <mass value="1.0"/>
                <inertia ixx="0.01" ixy="0" ixz="0"
                         iyy="0.01" iyz="0"
                         izz="0.01"/>
            </inertial>
        </link>
    </xacro:macro>

    <!-- LiDAR -->
    <xacro:macro name="lidar_link" params="prefix">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="0.03" length="0.02"/>
                </geometry>
                <material name="red"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="0.03" length="0.02"/>
                </geometry>
            </collision>

            <inertial>
                <mass value="0.1"/>
                <inertia ixx="0.001" ixy="0" ixz="0"
                         iyy="0.001" iyz="0"
                         izz="0.001"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name="imu_link" params="prefix">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <box size="0.03 0.03 0.01"/>
                </geometry>
                <material name="blue"/>
            </visual>

            <collision>
                <geometry>
                    <box size="0.03 0.03 0.01"/>
                </geometry>
            </collision>

            <inertial>
                <mass value="0.05"/>
                <inertia ixx="0.0005" ixy="0" ixz="0"
                         iyy="0.0005" iyz="0"
                         izz="0.0005"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="rear_right"/>
    <xacro:wheel_link prefix="rear_left"/>
    <xacro:wheel_link prefix="front_right"/>
    <xacro:wheel_link prefix="front_left"/>

    <xacro:lidar_link prefix="lidar"/>
    <xacro:imu_link prefix="imu"/>

    <joint name="base_rear_right_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <origin xyz="${-base_length/4} ${-(base_width + wheel_length)/2} 0"/>
    </joint>

    <joint name="base_rear_left_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <origin xyz="${-base_length/4} ${(base_width + wheel_length)/2} 0"/>
    </joint>

    <joint name="base_front_right_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${base_length/4} ${-(base_width + wheel_length)/2} 0"/>
    </joint>

    <joint name="base_front_left_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${base_length/4} ${(base_width + wheel_length)/2} 0"/>
    </joint>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="-0.09 0 ${sensor_height}" rpy="0 0 ${pi}"/>
    </joint>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.01 0 ${sensor_height}" rpy="0 0 0"/>
    </joint>

</robot>
